import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/Layout/Layout';
export default function Home() {
  return (
    <>
    <Head>
        <title>WhatsApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>     
      <Layout/>
      
    </>
  )
}